chore(linting): lint all commit messages to conventional commit standard
windranger-io/windranger-solidity-template pull request #105
Opened 2022-01-12 11:51 UTC by jasheal

### Purpose for this PR

Consistency and readability across all projects

2022-01-12 12:42 UTC, typicalbuster approved these changes

2022-01-12 12:51 UTC, bitparadigm approved these changes

2022-01-12 23:32 UTC, CjHare commented
question: Is this only going to lint messages only if people install the Husky hooks
question: does this enforce conventional commits in the GH UI when merging PRs?

In Git, when using PRs (with squashing, the way laid out in our processes) the commit message does not come from any of the individual commit messages, instead it's entered manually when the merging is performed.

As is, does change set enforce the conventional commit format on squashed PRs?

2022-01-12 23:47 UTC, CjHare requested changes
question (blocking): does this enforce conventional commits in the GH UI when merging PRs?

In Git, when using PRs (with squashing, the way laid out in our processes) the commit message does not come from any of the individual commit messages, instead it's entered manually when the merging is performed.

As is, does change set enforce the conventional commit format on squashed PRs?

2022-02-01 05:54 UTC, CjHare commented
Closing as discussed.

2022-02-01 05:54 UTC, closed without merging